##  Concatenation of the Arrays 

concatenation fonksiyonu:<br>
 iki veya daha fazla diziyi birlestirmek icin kullanilir.<br>
 Fonksiyonun ilk parametresi birlestirilecek dizilerin bir listesidir.<br>
 Ikinci parametre ise ,birlestirme islemlerinin hangi eksen veya boyuta gore yapilacagini  belirten bir parametredir.<br>
 ornek:
axis =0 parametresi dizilerin  satir bazinda (dikey birlestirme)
axis =1 parametresi  dizilerin sutun bazinda (yatay birlestirme)
saglar.<br>
    axis =0 ---> satir(dikey)<br>
    axis =1 ---> sutun (yatay)<br>

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [ ]:
# tek boyutlu diziler icin sadece axis =0 kullanilir. 

xy =np.concatenate((x,y), axis=1) # hata verir  
xy

In [7]:
# tek bir boyutta tek eksen var axis =0 
xy =np.concatenate((x,y),axis=0) 
xy

array([1, 2, 3, 4, 5, 6])

In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [10]:
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [11]:
np.concatenate((a,b),axis=None) # sutun 

array([1, 2, 3, 4, 5, 6, 7, 8])