# rand  & randn & randint

random.rand -->0-1 araliginda uniform dagitima sahip random float sayi uretir.Rastgele<br
Belirli bir araliktaki tum degerleri  yani 0 ile 1 araliginda olasiliklarin oldugu dagilim

random.randn --> ortalama degeri 0 ve standart sap,masi 1 olan normal dagilima sahip sayilar uretir.

random.randint-> belirtilen aralikta rastgele tamsayilar uretir.<br>
Bitis dahil degil

In [26]:
import numpy as np

In [4]:
np.random.rand(4,4)

array([[0.59697554, 0.7022348 , 0.63021453, 0.656735  ],
       [0.91188882, 0.453894  , 0.63624375, 0.5011747 ],
       [0.57152459, 0.63448063, 0.80465264, 0.24807536],
       [0.70742485, 0.38490734, 0.60942396, 0.87640223]])

In [6]:
np.random.randn(3,3)

array([[ 0.6059691 , -0.25805169,  0.44564633],
       [ 1.52522495, -0.53774549,  0.35179969],
       [-0.58202373, -0.23660578, -0.76381254]])

In [7]:
np.random.rand(50)

array([0.68496654, 0.13041226, 0.45904352, 0.30135532, 0.72967137,
       0.80332781, 0.05257156, 0.34330941, 0.60881724, 0.17499825,
       0.02106378, 0.05990795, 0.29276753, 0.91245174, 0.85406017,
       0.65358355, 0.89474209, 0.72295021, 0.36298282, 0.16471899,
       0.49696671, 0.64950973, 0.77996476, 0.95787403, 0.26269527,
       0.7830637 , 0.71246939, 0.46433495, 0.55454152, 0.11093529,
       0.51390641, 0.93224293, 0.46555886, 0.30390091, 0.33875315,
       0.21657705, 0.38915948, 0.22397722, 0.51606429, 0.45988461,
       0.82498059, 0.36766878, 0.71136265, 0.85077475, 0.67101486,
       0.60145081, 0.01723455, 0.53279202, 0.90519816, 0.17312318])

In [9]:
np.random.randn(1000).mean()

0.005498340175920351

In [10]:
np.random.randint(10) # 0 ile 10 arasinda int deger uretir,10 haric

3

In [11]:
np.random.randint(0,100,10)

array([46, 37, 83, 58, 79, 59, 47,  7, 15,  3])

In [12]:
np.random.randint(0,100, size=(2,4))

array([[44, 48, 99, 24],
       [94, 38, 38,  4]])

# max & argmax & min & argmin

## min 
dizideki en kucuk degeri dondurur.



In [14]:
# 0 dan baslayarak 10 kadar 10 deger olustur. 
myarr = np.random.randint(0,10,10)
myarr

array([5, 4, 9, 7, 6, 5, 6, 0, 0, 5])

In [15]:
myarr.min()

0

## max
Dizideki en buyuk degeri dondurur.

In [16]:
myarr.max()

9

## argmax 
 dizi icindeki en buyuk degerin indexini dondurur.

In [17]:
myarr.argmax()

2

# argmin 
dizi icindeki en kucuk degerin indexini dondurur.

In [18]:
myarr.argmin()

7

# size()
Bir dizideki toplam eleman sayisini verir.<br>
2x3 luk bir matrisin size =6 

In [35]:
arr =np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr.size

6

In [38]:
arr.shape

(2, 3)

In [39]:
arr.ndim

2

In [40]:
len(arr) # 

2

# itemsize()

Numpy dizisinde her bir elemanin bellekte kac byte kapladigini gosterir.<br>
Bu ozellik numpy dizisinin veri tipine baglidir ve bu veri tipiniun boyutuna gore degisir.<br>

itemsize--> bir numpy dizisinin bellekte kapladigi toplam alani hesaplamak icinde kullanilir.Bu hesaplama <br>
dizinin eleman sayisini itemsize ile carpimi ile hesaplanir.

In [41]:
arr.itemsize  # 


4

In [42]:
arr.dtype

dtype('int32')

In [43]:
arr.size

6

In [44]:
arr.size * arr.itemsize

24

# copy()
copy()==> Numpy dizisinde  bir kpya olusturmak icin kullanilir.<br>
Bu fonksiyon orjinal dizinin aynisini olusturur.Ancak bu kopya bagimsizdir.<br>
Yani kopya dizisi uzerinde yapilan herhangi bir degisiklik orjinal diziyi etkilemez.Orjinal dizi uzerinde yapilan degisiklikler de kopya dizsini etkilemez.


In [51]:
arr 

array([[33, 33, 33],
       [ 4,  5,  6]])

In [50]:
copyarr = arr.copy()
copyarr

array([[33, 33, 33],
       [ 4,  5,  6]])

In [47]:
arr[0] = 33 
arr 

array([[33, 33, 33],
       [ 4,  5,  6]])

In [52]:
copyarr

array([[33, 33, 33],
       [ 4,  5,  6]])

# transpose()
Numpy dizinerinin boyutlarini degistiren bir islevdir.Ozeellikle matrislerin transpozunu almak icin kullanilir.<br>
Bir matrisin transpozunu almak,matrisin satirlarini sutun,sutunlarini satir yapmaktir.
matrisin tranpozu--> satir--->sutun olur
                      sutun--->satir olur.

In [53]:
arr 

array([[33, 33, 33],
       [ 4,  5,  6]])

In [54]:
arr.transpose()

array([[33,  4],
       [33,  5],
       [33,  6]])

In [55]:
arr.T  # transpose alma 

array([[33,  4],
       [33,  5],
       [33,  6]])