## Split()
array_split() methodu:<br>
Numpy da bir diziyi belirtilen sayida esit olmayan parcalara bolmek icin kullanilir.<br>
Bu fonksiyon,diger fonksiyonlardan(hsplit,vsplit gibi) farkli olarak belilrl bir eksende degil,kullanicin belirrtigi sayida parcaya boler.<br>

vsplit() <br>
Numpyda bir diziyi   satirlar uzerinden birden cok parcaya ayirmak icin kullanilir.<br>

hsplit()<br>
Numpyda bir diziyi  sutunlar uzerinden birden cok parcaya ayirmak icin kullanilir.<br>
Temel olrak bir matrisi sutunlarini kulllanarak belirten indexlerde boler.<br>


In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
np.split(a,4)
#bolmek istedimiz array  ve kaca boleceksek o sayi yazilir
# yani 4 e bolmek istedik 4 yazdik

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [5]:
np.array_split(a,3) # 

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [6]:
x =np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
np.split(x,[1,3]) # farkli parcalar istiyoruz 
# burada x arrayi verdik 0 indexten  basla,1 e git,
# sonra 1 den 3.indexe kadar git,
# kalaninin da baska bir array yap

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]