# sort()

sort()methodu :<br>
Numerik ya da alfabetik array elemanlarini ,numerik veya alfabetik siraya gore siralamasini yapar.

In [2]:
import numpy as np

Elimizdeki  tek veya cok boyutlu hic farketmez,arrayi numerik veya alfabetik siralamak istersek,alfabetik olarak siralamak istersek ASCII  degerlerine gore siralma yapar.<br>
axis 0 -->satirlar<br>
axis 1 --> sutunlar<br>

In [4]:
a =np.array([2,4,3,5,1])
a

array([2, 4, 3, 5, 1])

In [5]:
np.sort(a)  # orjinal diziyi degistirmez

array([1, 2, 3, 4, 5])

In [6]:
a

array([2, 4, 3, 5, 1])

In [9]:
a.sort() # orjinal diziyi degistirmez
a

array([1, 2, 3, 4, 5])

In [10]:
myarr= np.random.randint(5,100,(3,3))
myarr

array([[23, 18, 39],
       [44, 79, 51],
       [90, 97,  5]])

In [11]:
# satirlar  yukaridan asagiya dogru satir satir siralanir.  
np.sort(myarr,axis=0) 

array([[23, 18,  5],
       [44, 79, 39],
       [90, 97, 51]])

In [12]:
# sutunlar soldan saga dogru sutun sutun siralanir. 
np.sort(myarr,axis=1) 

array([[18, 23, 39],
       [44, 51, 79],
       [ 5, 90, 97]])

In [13]:
# none yapildiginda tek bir boyuta geririr. 
np.sort(myarr,axis=None)

array([ 5, 18, 23, 39, 44, 51, 79, 90, 97])