# Array()

array() fonk. kullanarak bir NumPy "ndarray" nesnesi olusturabiliriz.<br>
np.array() ---> bu fonk. python listelerini,tuplari ya da diger dizi vb..veri yapilarini NumPy dizisine(array)  donusturmek icin kullanilir.<br>


# dtyep()

dtype --->  dizide saklanacak olan  ogelerin veri tipini belirler<br>
ornek: float,int,complex.Eger belirtilmezse NumPy,veri tipini veriye gore otomatik belirler.

In [1]:
import numpy as np

# create array

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_list2 = ([1,2,3],[4,4,6],[7,8,9],[10,11,12])
my_list2

([1, 2, 3], [4, 4, 6], [7, 8, 9], [10, 11, 12])

In [5]:
my_arr2 =np.array(my_list2) # 4 satir 4 sutundan olusan 2 boyutlu array
my_arr2

array([[ 1,  2,  3],
       [ 4,  4,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Bir Dizinin Boyutunu Alma  
### shape & reshape

### shape()

NumPy array boyutunu yani kac satir ve sutundan olustugunu gosteren bir tuple dondurur.Esasen her eksendeki elemanlarin sayisini dondurur.<br>
Bu tupledeki sayilar,dizidseki her bir boyutundaki oge sayisini gosterir.<br>
ornek : (m, n) tuple bakarsak m satir ve n sutundan olusan matrisi temsil eder.<br>


### reshape()

NumPy array' i yeniden sekillendirmek istedigimizde  yani satir ve sutun sayisini degistirmek istedigimizde "reshape" fonk.kullaniriz.
Diziyi belirten yeni sekle sokar,ancak bu metot, orjinal veriyi degistirmez.<br>
Belirtilen boyutlar icin "-1" degeri kullanilabilir.Boylece numpy otomatik olrak belirtilen  diger boyutlara uygub sekilde bu boyutu hesaplar.<br>


In [ ]:
np.shape(2,3) # 2 satir 3 sutun 

In [9]:
my_arr2

array([[ 1,  2,  3],
       [ 4,  4,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
my_arr2.shape  # array boyutunu alma 
                # parantez koyarsak hata aliriz.

(4, 3)

In [7]:
np.shape(my_arr2) # array boyutunu alma 

(4, 3)

In [6]:
my_arr2.reshape(2,6) # array i boyutunu degistirme 2 satir 6 sutun

array([[ 1,  2,  3,  4,  4,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [13]:
my_arr2.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 4],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [15]:
my_arr2.reshape(3,-1) # satiri soyleyip sutun belirmiyorsak 
                      #-1 yazabiliriz.

array([[ 1,  2,  3,  4],
       [ 4,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
my_arr2.reshape(-1,6)

array([[ 1,  2,  3,  4,  4,  6],
       [ 7,  8,  9, 10, 11, 12]])

# ndim & ndmin 

### ndim 
Bir numpy array in boyutunu gosterir.


## ndmin 
ndmin--> minimum dimension  ifadesinin kisatmasidir.<br>
Olusturulacak dizinin en az kac boyutlu oldugunu gosterir<br>
Eger verilen veri belirtlen boyutun altinda ise eksik boyutlar otomatik olarak eklenir<br>
Bu durum,daha yuksek boyutlu bir diziye islem yapmak istendiginde,fakat verinin bu boyutta olmadiginda kullanislidir.

In [18]:
arr0 = np.array(5)
arr1 = np.array([1,2,3,4])
arr2 = np.array([[1,2],[3,4]])
arr3 = np.array([[[1,2],[3,4],[5,6]]])

In [19]:
arr0.ndim
arr1.ndim  # en son yazilan kod ciktisini verir.

1

In [20]:
print(arr0.ndim)    # arr boyutlarini verir.
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [2]:
mylist = list(range(0,24))

In [3]:
mylist

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23]

In [4]:
myarray= np.array(mylist)
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [6]:
myarray2=np.array(mylist,ndmin=4)  # 4 boyutlu olusturduk. 
myarray2

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15, 16, 17, 18, 19, 20, 21, 22, 23]]]])

In [7]:
myarray.shape

(24,)

# dtype & astype()

### dtype 
dtype yani data type bir ndarray de saklanan verinin turunu belirtir.<br>


### astype()
astype()--> bir ndarray metodudur.
            mevcut bir ndarray in veri tipini degistirmek icin kullanilir.<br>
astype metodu,verinin yeni bir kopyasini olusturup,yeni veri tipine donusturur.Orjinal dizi degismez<br>            

# NumPy Data Type

a -integer (1)
b- float   (2.0)
c- complex  (3+4j)
d- Boolean  True

dtype int ,variants --> int8,int16,int32,int64 ---Integers<br>
dytpe uint,variats->    uint8,uint16,uint32,uint64-->unsigned integers  
bool Bool  ---Boolean   true ,False   

float--> float16,float32,float64,float128--Floating -point <br>
complex-->complex64,complex128,complex256  ...complex 

In [8]:
myint =np.array([1,2,3])
myint

array([1, 2, 3])

In [9]:
myint.dtype

dtype('int32')

In [15]:
myfloat= np.array([1,2,3,4.5])
myfloat


array([1. , 2. , 3. , 4.5])

In [12]:
myfloat.dtype

dtype('int32')

In [16]:
x = np.array([1,2],dtype="float64") # float cevirme dtype = ile
x

array([1., 2.])

In [17]:
newx = x.astype("i")  # 
newx

array([1, 2], dtype=int32)

In [18]:
newx2 =x.astype("bool")
newx2

array([ True,  True])

In [19]:
newx3 = x.astype("f")
newx3

array([1., 2.], dtype=float32)

# resize()

ndarray nesnesinin boyutunu yeniden sekillendirmek icin kullanilir.<br>
resize--> yontemi ndarray nesnesinin boyutunu degistirir.<br>
          Yeni boyutlara uygun olarak verileri degistirir.<br>
          

In [20]:
arr =np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.resize(arr,(2,2)) # 2 satir 2 sutun yaptik

array([[1, 2],
       [3, 4]])

In [ ]:
np.reshape(arr(6,3))# hata verir veri sayisi uygun degil

In [25]:
np.resize(arr,(6,3)) # bagimsiz fonk. olarak kullanilirsa veriyi
                    # tekrar eder.Sifirlarla doldurmaz

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [26]:
# olustirdugumuz array in bir yontemi olarak calisir,verileri tekrar etmez
# sifirlar ile doldurur. 
arr2 =np.array([[1,2,3],[4,5,6]])
arr2.resize(6,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# arange()


Python da range() fomksiyoinuna benzer.<br>
Belirtilen baslangic degerinden baslar,her defasinda adim sayisi kadar artirir.Bitis degerine kadar olan bulunduran bir numpy dizsi dondurur.<br>
** bitis degeri diziye dahil edilmez.**<br>

In [27]:
np.arange(0,10) # 10 kadar 10 dahil 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(10) # sifir degerini yazmasak da olur.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(0,50,10) #0 dan basla 50 ye kadar 10 ar 10 ar git

array([ 0, 10, 20, 30, 40])

In [30]:
np.arange(0,10,2) # 50 ye kadar olan cift sayilari yaz 

array([0, 2, 4, 6, 8])

In [31]:
np.arange(1,10,2)# tek sayilari bulma

array([1, 3, 5, 7, 9])

In [32]:
np.arange(0,10,2.5) # 10 a kadar 2.5 li olusturma 

array([0. , 2.5, 5. , 7.5])

In [33]:
np.arange(start=0,stop=10,step=2)

array([0, 2, 4, 6, 8])

# linspace()

Verilen baslangic ve bitis degerleri arasinda belirtilen sayida esit aralikta degerlerden olusan bir numpy dizisi olusturur.<br>
linspace fonk. ozellile grafik cizme  ve veri analizi gibi durumlarda kullanilr.<br>

In [34]:
np.linspace(1,20) # esit aralikli sayilar dondurur. 
# belirtilmezse, default degeri 50 yani 50 tane sayi uretir

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [36]:
np.linspace(0,20,5) # burada 5 tane yazildi default 5  

array([ 0.,  5., 10., 15., 20.])

In [37]:
np.linspace(1,20,5, dtype=int) # int sayilar istedik 

array([ 1,  5, 10, 15, 20])

In [38]:
np.linspace(1,20,4, dtype="i") 
# arange den farki 20 dahil etti. endpoint default true 

array([ 1,  7, 13, 20], dtype=int32)

In [40]:
np.linspace(1,20,5, endpoint= True) 
# endpoint True dersek 20 dahil edilir. 

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [41]:
np.linspace(1,20,5, endpoint=False)
# endpoint False degerinde 20 dahil edilmedi.

array([ 1. ,  4.8,  8.6, 12.4, 16.2])

In [39]:
np.linspace(0,20,5,dtype="bool")

array([False,  True,  True,  True,  True])

In [42]:
np.linspace(1,20,5, endpoint=False, retstep= True)
# araliklar arasinda deger  verme 

(array([ 1. ,  4.8,  8.6, 12.4, 16.2]), 3.8)

# logspace()

logaritmik araliklarla dizi olusturur.<br>
logspace linspace fonksiyonuna benzer sekilde calisir.Ancak araliklar logaritmik olrak hesaplanir.<br>
Logspace: start degeri 10a, stop degeri 10b olan n elemanli ve elemanlarin arasindaki katlari esit olan bir dizi olusturur.<br>

In [43]:
np.logspace(2,3)
#logaritmik olrak bize 10^2(100) ve 10^3(1000 olan 50 tane sayi olusturacak
# default olarak  50 tane,10 luk  logaritmik araliklarla sayi olusturur. 
#

array([ 100.        ,  104.81131342,  109.8541142 ,  115.13953993,
        120.67926406,  126.48552169,  132.57113656,  138.94954944,
        145.63484775,  152.64179672,  159.98587196,  167.68329368,
        175.75106249,  184.20699693,  193.06977289,  202.35896477,
        212.09508879,  222.29964825,  232.99518105,  244.20530945,
        255.95479227,  268.26957953,  281.1768698 ,  294.70517026,
        308.88435965,  323.74575428,  339.32217719,  355.64803062,
        372.75937203,  390.69399371,  409.49150624,  429.19342601,
        449.8432669 ,  471.48663635,  494.17133613,  517.94746792,
        542.86754393,  568.9866029 ,  596.36233166,  625.05519253,
        655.12855686,  686.648845  ,  719.685673  ,  754.31200634,
        790.60432109,  828.64277285,  868.51137375,  910.29817799,
        954.09547635, 1000.        ])

In [4]:
np.logspace(2,3, num=10,base=2)

array([4.        , 4.32023896, 4.66611616, 5.0396842 , 5.44316   ,
       5.87893797, 6.34960421, 6.85795186, 7.4069977 , 8.        ])

# zero & zeros_like()

zeros--> Belirtilen satir ve sutuna sahip 0'lardan olusan bir matris dondurur.

In [6]:
# 3 satir 2 sutun 
np.zeros((3,2)) # o lardan matrix dondurur

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

zeros_like()--> verilen bir diziyle ayni sekil ve turde fakat tum elemanlari 0 olan bir dizi  olusturur.

In [8]:
np.zeros(5) # tek boyutlu array

array([0., 0., 0., 0., 0.])

In [9]:
arr =np.arange(12).reshape(4,3)
arr 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.zeros_like(arr)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# ones & ones_like()

In [13]:
np.ones((3,5)) # 3 satir 5 sutun 1 lerden olusan array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.ones_like(arr)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# eye()

eye()fonk.--> belirtlien boyutta bir birim matris olusturur.<br>
Birim matriste ana kosegen uzerindeki elemanlar 1 dir.Diger tum elemanlar 0 dir.

In [17]:
np.eye(3) # 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3,k=1)
#burada  k degerine 1 verdigimizde sifirinci indeksten degil
# 1.indexten basla diyoruz

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
np.eye(3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.eye(3,k=-1) # -1 verdigimizde satir bazinda alt kisimdan baslar

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [23]:
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

# full() & full_like()

full()--> Belirtilen sekle ve diziye sahip bir dizi olusturur.<br>
full_like()---> Verilen dizinin sekil ve turune sahip ,ancak belirtilen degerle doldurulmus bir dizi olusturur.

In [24]:
np.full((3,3),55,dtype=int)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [ ]:
np.full_like(2,2)
# hangi degerler ile belirtilmedigi icin hata verir.

In [26]:
np.full([2,2],10)

array([[10, 10],
       [10, 10]])

In [27]:
np.full_like(arr,2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [28]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])