# NumPy Indexing & Selection 

NumPy dizilerinde belilrli bir elemana ulasmak icin dizi adini yazdiktan sonra,koseli parantez icinde ilgili elemanin index numarasi yazilir,belirtilir.<br>
orn : myarr[indexNo] <br>

Index numaralri 0 dan baslar,yani ilk eleman indexi 0 dir.Diger elemanlarin indexi sirasiyla 1,2,3,4 diye devam eder.<br>

Negatif indexleme de kullanilabilir.Negatif indexleme,NumPy dizilerinde sondan baslayarak elemanlara erismek icin kullanilir.
Son elemanin indexi -1 dir.Sondan bir onceki elemanin indexi -2,-3 gibi devam eder.<br>

2 boyutlu NumPy dizilerinde,belirli bir elemana ulasmak icin,satir ve sutun numaralari kullaniriz.<br>
orn: myarr [satirNo,sutunNo] formati kullanilir.<br>

3 boyutlu NumPy dizilerinde elemanlara erismek icin derinlik,satir ve sutun numaralari kullanilir<br>
orn: myarr[derinlikNo,satirNo,sutunNo] formati kullanilir.



## Bracket indexing & Selection 
Bir dizinin bir veya birkac ogesini secmenin en basit yolu Python listelerindeki gibi yapilir.

In [8]:
import numpy as np

In [2]:
arr =np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [3]:
arr[5] # 5. indexteki elemana ulasmak isitorsak 5.indexi yazariz

5

In [4]:
arr[10]

10

In [5]:
arr[-2] # sondan ikinci index

22

In [6]:
# 0 indexten 5. index e kadar olanlari getirelim
arr [0:5]


array([0, 1, 2, 3, 4])

In [11]:
import numpy as np

In [13]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr_2d[1]

array([4, 5, 6])

In [15]:
arr_2d[0]

array([1, 2, 3])

In [16]:
arr_2d[2]

array([7, 8, 9])

In [17]:
arr_2d[-1]

array([7, 8, 9])

In [18]:
arr_2d[1][2]

6