In [1]:
import numpy as np 

In [2]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# 2,5,8 i nasil getirebiliriz
arr_2d[:,1]

array([2, 5, 8])

In [6]:
arr_2d[:,2]  # 0 index,2.sutun 

array([3, 6, 9])

In [9]:
# 4,5,6 i nasil getirebiliriz.
arr_2d[1:2]

array([[4, 5, 6]])

In [13]:
#7,8,9 getirelim
arr_2d[:,2]

array([3, 6, 9])

In [18]:
#(2,3)(5,6) nasil getirilir
arr_2d[:2,1:]  # solda satir ,sagda sutun

array([[2, 3],
       [5, 6]])