# Fancy Index 

NumPy dizilerinde <br>
   bir veya daha fazla kosula veya <br>
   belirtilen indexler listesine gore<br>
   dizideki belilrl elemanlara erismek icin <br>
   kullanilan bir indexleme yontemidir.<br>

   Fancy index yonteminde<br>
   Koseli parantez icinde<br>
   bir liste veya dizi kullanilarak dizinin belilrl elemanlarina ulasilir<br>
   Fancy index yontemi normal indexleme yontemlerine gore daha esnek ve daha gucludur.

      

In [1]:
import numpy as np

In [2]:
a =np.arange(0,30,3)
a 

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
 a[0]

0

In [4]:
a[5]

15

In [5]:
a[3]

9

In [7]:
a[1],a[3],a[5]

(3, 9, 15)

In [8]:
a[[1,3,5]]

array([ 3,  9, 15])

In [ ]:
a[1,3,5] # tek koseli parantezde hata verir.arr 
         # satir sutun ve derinlik olarak anlar.

In [10]:
arr =np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [11]:
arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr[[3,0,5]] # 3.satir 0.satir ve 5.satir getirelim

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [13]:
arr[  :  ,[3,0,5]]  # virgulun sol taraf satir,sag taraf sutun 

array([[ 3,  0,  5],
       [13, 10, 15],
       [23, 20, 25],
       [33, 30, 35],
       [43, 40, 45],
       [53, 50, 55],
       [63, 60, 65],
       [73, 70, 75],
       [83, 80, 85],
       [93, 90, 95]])

In [14]:
# 50,55 getir 
arr[[5,5],[0,5]]

array([50, 55])

In [15]:
arr[5,[0,5]]

array([50, 55])