# Selection & Condation



In [1]:
import numpy as np

In [2]:
arr =np.arange(5,15)
arr 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
arr > 10

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [7]:
arr [arr>10]  # dizide 10 dan buyuk elemanlari getir

array([11, 12, 13, 14])

In [11]:
# dizide 10 dan kucuk elemanlari getir
arr [arr < 10]

array([5, 6, 7, 8, 9])

In [14]:
arr[(arr < 10)& (arr != 5)]

array([6, 7, 8, 9])