# Broadcasting 

Broadcasting farkli  sekillerdeki numpy dizileri uzerinde aritmetik islemler yapmak icin kullanilan bir ozelliktir.<br>
Broadcasting ozelligi:<br>
Islem yapmak icin iki dizinin sekillerinin tam olarak eslesmesi <br>
gerektigi durumlarda Numpy islemi otomatik olarak yuruterek daha esnek  sekilde islem yapilmasini saglar.<br>
Broadcasting islemi daha kucuk boyutlu bir dizi ile daha buyuk boyutlu bir dizi arasinda gerceklestirilir.<br>
Bu islemde daha kucuk boyutlu dizi,diger diziye uyarlanarak islem yapilabilir hale getirilir.







In [1]:
import numpy as np 

In [2]:
arr =np.arange(1,11)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[:5] #  )  0 dan baslayarak 5 e kadar  git 

array([1, 2, 3, 4, 5])

In [4]:
arr[:5]=77  # broadcasting yaparak 77 i 1 e 2 3 e yaydik
arr 

array([77, 77, 77, 77, 77,  6,  7,  8,  9, 10])

In [5]:
a = [0,2,4,6,8,10]
a

[0, 2, 4, 6, 8, 10]

In [6]:
a[0:3]   

[0, 2, 4]

In [ ]:
a[0:3]=100 # python da bunu yapamayiz.hata verir 