### Arithmatic Operators Implemented in Numpy 

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr1 = np.arange(15)
arr1 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
arr + arr 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.add(arr,arr)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
arr /.15 

array([ 0.        ,  6.66666667, 13.33333333, 20.        , 26.66666667,
       33.33333333, 40.        , 46.66666667, 53.33333333, 60.        ])